apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-app
spec:
  selector:
    matchLabels:
      app: docker
  replicas: 2
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
        - name: docker-app
          image: docker-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080