apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-app
spec:
  selector:
    matchLabels:
      app: docker
  replicas: 2
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
        - name: docker-app
          image: docker-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: docker-app-service
spec:
  type: NodePort
  selector:
    app: docker
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30002